### ISSUE TITLE
[!] UNKNOWN PROTOCOL PART: ERROR :Closing link

### ISSUE THREAD

**Issue by donSchoe** [v2px/fantasy-irc#3]
--> ERROR :Closing link: (ringo@simbpro.com) [Ping timeout: 121 seconds]
[!] UNKNOWN PROTOCOL PART: ERROR :Closing link: (ringo@simbpro.com) [Ping timeout: 121 seconds]

Any idea why it keeps crashing?

https://gist.github.com/donSchoe/5181077

**Comment by v2px** [comment]
Is this still happening with Ruby 2.3?

**Comment by 5chdn** [comment]
running stable for 2 days now.
